[package]
name = "client_utils"
version = "0.1.0"
edition = "2024"

[dependencies]
mockall.workspace = true
serde.workspace = true
serde_json.workspace = true
ureq.workspace = true

[dev-dependencies]
assertor.workspace = true
