[package]
name = "broker"
version = "0.1.0"
edition = "2024"

[dependencies]
coordinator = { path = "../coordinator" }
protocol = { path = "../protocol" }
tokio.workspace = true
walkdir.workspace = true

[dev-dependencies]
assertor.workspace = true
file_test_utils = { path = "../file_test_utils" }