[package]
name = "broker"
version = "0.1.0"
edition = "2024"

[dependencies]
walkdir.workspace = true
protocol = { path = "../protocol" }

[dev-dependencies]
assertor.workspace = true
file_test_utils = { path = "../file_test_utils" }