[package]
name = "broker"
version = "0.1.0"
edition = "2024"

[dependencies]
walkdir = "2.5.0"

[dependencies.uuid]
version = "1.18.1"
# Lets you generate random UUIDs
features = ["v4"]

[dev-dependencies]
assertor = "0.0.4"